--Queries

SELECT * FROM viewAll;

SELECT * FROM (SELECT * From GROUP1 ORDER BY ID DESC) WHERE ROWNUM<=20

SELECT name, mempoints FROM (SELECT name, mempoints FROM MEMBERSHIP ORDER BY MEMPOINTS DESC) 
	WHERE ROWNUM<=5 ORDER BY MEMPOINTS DESC;