insert into Group1 (id, restname, rating) values (1, 'Talons', 5);
insert into Group1 (id, restname, rating) values (2, 'Wendys', 9);
insert into Group1 (id, restname, rating) values (3, 'Popeyes', 8);
insert into Group1 (id, restname, rating) values (4, 'Mcdonalds', 2);
insert into Group1 (id, restname, rating) values (5, 'TacoBells', 7);
insert into Group1 (id, restname, rating) values (6, 'Licks', 5);
insert into Group1 (id, restname, rating) values (7, 'Joyee', 10);
insert into Group1 (id, restname, rating) values (8, 'Lots', 3);
insert into Group1 (id, restname, rating) values (9, 'Napoleon', 10);
insert into Group1 (id, restname, rating) values (10, 'Ruben', 10);
insert into Group1 (id, restname, rating) values (11, 'Tony', 10);
insert into Group1 (id, restname, rating) values (12, 'White Castle',4);
insert into Group1 (id, restname, rating) values (13, 'Krispy Cream', 9);
insert into Group1 (id, restname, rating) values (14, 'Subway', 6);
insert into Group1 (id, restname, rating) values (15, 'Loves', 9.5);
insert into Group1 (id, restname, rating) values (16, 'IIT', 5.5);
insert into Group1 (id, restname, rating) values (17, 'SOS', 4.5);
insert into Group1 (id, restname, rating) values (18, 'Girl and the Goat', 7.5);
insert into Group1 (id, restname, rating) values (19, 'Moms', 10);
insert into Group1 (id, restname, rating) values (20, 'Dads', 6);
insert into Group1 (id, restname, rating) values (21, 'Bros', 9);
insert into Group1 (id, restname, rating) values (22, 'Disney', 7);
insert into Group1 (id, restname, rating) values (23, 'Shell', 9.9);
insert into Group1 (id, restname, rating) values (24, 'Yo', 8.9);
insert into Group1 (id, restname, rating) values (25, 'HI', 3);
insert into Group1 (id, restname, rating) values (26, 'Nice', 6);
insert into Group1 (id, restname, rating) values (27, 'LoL', 2);
insert into Group1 (id, restname, rating) values (28, 'League', 1.5);
insert into Group1 (id, restname, rating) values (29, 'Bdubs', 8);
insert into Group1 (id, restname, rating) values (30, 'Wing Stop', 9);
insert into Group2 (id, laptopname, brand, numofcomments) values (1, 'Link', 'Dell', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (2, 'YOLO', 'HP', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (3, 'Swag', 'Apple', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (4, '626', 'Lenovo', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (5, 'Mac', 'Acer', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (6, 'Gragas', 'Founder', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (7, 'Jinx', 'Hasee', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (8, 'Xnote', 'HCL', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (9, 'Znote', 'Lanix', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (10, 'Fuji', 'Getac', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (11, 'Pugz', 'Medion', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (12, 'German', 'Lemote', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (13, 'Napoleon', 'Dell', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (14, 'Tony', 'HP', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (15, 'Ruben', 'Lenovo', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (16, 'Tabz', 'HCL', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (17, 'Bess', 'Lanix', 1);
insert into Group2 (id, laptopname, brand, numofcomments) values (18,  'Avi', 'Getac', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (19, 'Air', 'Hasee', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (20, 'Six', 'Lemote', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (21, 'Tech', 'Founder', 1);
insert into Group2 (id, laptopname, brand, numofcomments) values (22, 'Illi', 'Acer', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (23, 'CHI', 'Medion', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (24, 'Siana', 'Hasee', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (25, 'Gator', 'HCL', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (26, 'Lou', 'Lanix', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (27, 'Chim', 'Getac', 1);
insert into Group2 (id, laptopname, brand, numofcomments) values (28, 'Z', 'Lenovo', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (29, 'Line', 'Dell', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (30, 'Vase', 'HP', 1);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (1, 'Henry Johnson', 'HenryJ', 'HJohnson@yahoo.com', to_date('2013-12-13', 'yyyy-mm-dd'), 1000, 76);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (2, 'David Medina', 'DavidM', 'DMedina@hotmail.com', to_date('2013-12-20', 'yyyy-mm-dd'), 875, 50);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (3, 'Jorge Barrientos', 'JorgeB', 'JBarrientos@gmail.com', to_date('2014-01-01', 'yyyy-mm-dd'), 200, 45);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (4, 'Maliq Hinez', 'MaliqH', 'MHinez@yahoo.com', to_date('2014-01-05', 'yyyy-mm-dd'), 400, 43);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (5, 'John Doe', 'JohnD', 'JDoe@yahoo.com', to_date('2014-01-18','yyyy-mm-dd'), 1500, 35);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (6, 'Mary Jane', 'MaryJ', 'MJane@hotmail.com', to_date('2014-01-30', 'yyyy-mm-dd'), 300, 33);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (7, 'Jane Doe', 'JaneD', 'JDoe2@yahoo.com', to_date('2014-02-01', 'yyyy-mm-dd'), 575, 30);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (8, 'Sarah Love', 'SarahL', 'SLove@gmail.com', to_date('2014-02-08', 'yyyy-mm-dd'), 2000, 28);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (9, 'French Fries', 'FrenchF', 'FFries@outlook.com', to_date('2014-02-15', 'yyyy-mm-dd'), 775, 21);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (10, 'Every Day', 'EveryD', 'EDay@yahoo.com', to_date('2014-02-28', 'yyyy-mm-dd'), 666, 20);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (11, 'One Stop', 'OneS', 'OStop@gmail.com', to_date('2014-03-02', 'yyyy-mm-dd'), 3000, 15);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (12, 'Pikachu', 'Pikachu', 'Pikachu@yahoo.com', to_date('2014-03-04', 'yyyy-mm-dd'), 2200, 13);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (13, 'Jinx', 'Jinx', 'Jinx@gmail.com', to_date('2014-03-08', 'yyyy-mm-dd'), 555, 10);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (14, 'Bronze', 'Bronze', 'Bronze@hotmail.com', to_date('2014-03-05', 'yyyy-mm-dd'), 4000, 10);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (15, 'Samsung', 'Samsung', 'Samsung@yahoo.com', to_date('2014-03-28', 'yyyy-mm-dd'), 800, 9);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (16, 'Vans', 'Vans', 'Vans@gmail.com', to_date('2014-04-16', 'yyyy-mm-dd'), 999, 7);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (17, 'Vase', 'Vase', 'Vase@hotmail.com', to_date('2014-04-17', 'yyyy-mm-dd'), 190, 5);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (18, 'Yellow', 'Yellow', 'Yellow@yahoo.com', to_date('2014-04-20', 'yyyy-mm-dd'), 900, 3);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (19, 'Cal', 'Cal', 'Cal@gmail.com', to_date('2014-05-03', 'yyyy-mm-dd'), 789, 0);
insert into Membership (id, name, password, email, dateofreg, balance, mempoints) values (20, 'Muneeb', 'Muneeb', 'Muneeb@yahoo.com', to_date('2014-05-13', 'yyyy-mm-dd'), 5000, 0);