insert into Group1 (id, restname, rating) values (1, 'Talons', 5);
insert into Group1 (id, restname, rating) values (2, 'Wendys', 9);
insert into Group1 (id, restname, rating) values (3, 'Popeyes', 8);
insert into Group1 (id, restname, rating) values (4, 'Mcdonalds', 2);
insert into Group1 (id, restname, rating) values (5, 'TacoBells', 7);
insert into Group1 (id, restname, rating) values (6, 'Licks', 5);
insert into Group1 (id, restname, rating) values (7, 'Joyee', 10);
insert into Group1 (id, restname, rating) values (8, 'Lots', 3);
insert into Group1 (id, restname, rating) values (9, 'Napoleon', 10);
insert into Group1 (id, restname, rating) values (10, 'Ruben', 10);
insert into Group1 (id, restname, rating) values (11, 'Tony', 10);
insert into Group1 (id, restname, rating) values (12, 'White Castle',4);
insert into Group1 (id, restname, rating) values (13, 'Krispy Cream', 9);
insert into Group1 (id, restname, rating) values (14, 'Subway', 6);
insert into Group1 (id, restname, rating) values (15, 'Loves', 9.5);
insert into Group1 (id, restname, rating) values (16, 'IIT', 5.5);
insert into Group1 (id, restname, rating) values (17, 'SOS', 4.5);
insert into Group1 (id, restname, rating) values (18, 'Girl and the Goat', 7.5);
insert into Group1 (id, restname, rating) values (19, 'Moms', 10);
insert into Group1 (id, restname, rating) values (20, 'Dads', 6);
insert into Group1 (id, restname, rating) values (21, 'Bros', 9);
insert into Group1 (id, restname, rating) values (22, 'Disney', 7);
insert into Group1 (id, restname, rating) values (23, 'Shell', 9.9);
insert into Group1 (id, restname, rating) values (24, 'Yo', 8.9);
insert into Group1 (id, restname, rating) values (25, 'HI', 3);
insert into Group1 (id, restname, rating) values (26, 'Nice', 6);
insert into Group1 (id, restname, rating) values (27, 'LoL', 2);
insert into Group1 (id, restname, rating) values (28, 'League', 1.5);
insert into Group1 (id, restname, rating) values (29, 'Bdubs', 8);
insert into Group1 (id, restname, rating) values (30, 'Wing Stop', 9);
insert into Group2 (id, laptopname, brand, numofcomments) values (1, 'Link', 'Dell', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (2, 'YOLO', 'HP', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (3, 'Swag', 'Apple', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (4, '626', 'Lenovo', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (5, 'Mac', 'Acer', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (6, 'Gragas', 'Founder', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (7, 'Jinx', 'Hasee', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (8, 'Xnote', 'HCL', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (9, 'Znote', 'Lanix', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (10, 'Fuji', 'Getac', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (11, 'Pugz', 'Medion', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (12, 'German', 'Lemote', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (13, 'Napoleon', 'Dell', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (14, 'Tony', 'HP', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (15, 'Ruben', 'Lenovo', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (16, 'Tabz', 'HCL', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (17, 'Bess', 'Lanix', 1);
insert into Group2 (id, laptopname, brand, numofcomments) values (18,  'Avi', 'Getac', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (19, 'Air', 'Hasee', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (20, 'Six', 'Lemote', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (21, 'Tech', 'Founder', 1);
insert into Group2 (id, laptopname, brand, numofcomments) values (22, 'Illi', 'Acer', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (23, 'CHI', 'Medion', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (24, 'Siana', 'Hasee', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (25, 'Gator', 'HCL', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (26, 'Lou', 'Lanix', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (27, 'Chim', 'Getac', 1);
insert into Group2 (id, laptopname, brand, numofcomments) values (28, 'Z', 'Lenovo', 2);
insert into Group2 (id, laptopname, brand, numofcomments) values (29, 'Line', 'Dell', 3);
insert into Group2 (id, laptopname, brand, numofcomments) values (30, 'Vase', 'HP', 1);